### ISSUE TITLE
tr in td issue

### ISSUE THREAD

**Issue by sgmbr** [nicoleilustre/aerial-calendar#12]
https://github.com/nicoleilustre/aerial-calendar/blob/b54395195beb4cdbde7c522248fa6e77b4196b01/src/components/IndividualClass.tsx#L10

This really needs to be fixed.

The easiest acceptable fix would be using div instead of tr + td in this component

but properly fixing this (iterate through first row of each day, then second row...) would be a good practice.

**Comment by nicoleilustre** [comment]
DOne
