### ISSUE TITLE
listOfClasses is not DRY

### ISSUE THREAD

**Issue by sgmbr** [nicoleilustre/aerial-calendar#14]
https://github.com/nicoleilustre/aerial-calendar/blob/b54395195beb4cdbde7c522248fa6e77b4196b01/src/pages/bookedClassespage.tsx#L5

https://github.com/nicoleilustre/aerial-calendar/blob/b54395195beb4cdbde7c522248fa6e77b4196b01/src/pages/classDetails.tsx#L12

Same thing in two places. Make it a function and put it in a separate file.

**Comment by nicoleilustre** [comment]
Done
