### ISSUE TITLE
Define props type

### ISSUE THREAD

**Issue by sgmbr** [nicoleilustre/aerial-calendar#5]
https://github.com/nicoleilustre/aerial-calendar/blob/b54395195beb4cdbde7c522248fa6e77b4196b01/src/pages/homepage.tsx#L10

https://github.com/nicoleilustre/aerial-calendar/blob/b54395195beb4cdbde7c522248fa6e77b4196b01/src/components/BookingForm.tsx#L16

...and other places

**Comment by nicoleilustre** [comment]
Done
